version: 0.0
os: windows
files:
  - source: ./helloworldservice-0.0.1-SNAPSHOT.jar
    destination: C:\Users\Administrator\Downloads\Deploy
hooks:
  BeforeInstall:
    - location: Deploy/clean.bat
      runas: administrator
 ApplicationStart:
     - location: Deploy/run.bat       
       runas: administrator


